apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-blue
  namespace: hello-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      version: blue
  template:
    metadata:
      labels:
        app: postgres
        version: blue
    spec:
      containers:
      - name: postgres
        image: 785637365112.dkr.ecr.us-east-1.amazonaws.com/eks-capstone:eks-capstone-app-v2
        ports:
        - containerPort: 5432
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "300m"
            memory: "512Mi"
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        - name: POSTGRES_DB
          value: hello_db
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
          subPath: postgres-db
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
